spring.application.name=BookMyShow

spring.datasource.url=jdbc:mysql://localhost:3306/BookMyShowDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=surya123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082
